site_name: lamatrix
nav:
    - Home: README.md

theme:
  name: "material"
  icon:
      logo: material/matrix
  palette:
    scheme: default
    primary: deep purple
    accent: indigo
repo_url: https://github.com/christinahedges/lamatrix
plugins:
  - search
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences